### PR TITLE
Ability to Join Classroom Added

### LINKED ISSUE #9: Ability to join classroom

### PR DESCRIPTION
**Pull request by Om-Gujarathi**

### CODE REVIEW

**Review by shatanikmahanty — CHANGES_REQUESTED** [review]
Please refrain from using hardcoded values for sdk version in build.gradle. Use them through configured values in local.properties file

**Comment by shatanikmahanty** [comment]
```
sdk.dir=D:\\Android\\SDK
flutter.sdk=D:\\flutter
flutter.buildMode=debug
flutter.versionName=1.0.0
flutter.versionCode=1
flutter.minSdkVersion=24
flutter.targetSdkVersion=33
flutter.compileSdkVersion=33
```

This is how it should look like. Use the given configuration, but make sure to replace it with your sdk paths. Also, make sure not to add the file in your commit as it contains user dependent paths.

**Comment by Om-Gujarathi** [comment]
> Please refrain from using hardcoded values for sdk version in build.gradle. Use them through configured values in local.properties file

Yes I have made the requested changes.

**Review by shatanikmahanty — APPROVED** [review]
LGTM! Ready to merge 🚀

**Pull request merged**
